IF(POCO_FOUNDATION_INCLUDE_DIR AND POCO_FUNDATION_LIB )
   SET(POCO_FOUNDATION_FOUND TRUE)
   
ELSE(POCO_FOUNDATION_INCLUDE_DIR AND POCO_FUNDATION_LIB )
  
  IF(WITH_POCO_FOUNDATION )
    FIND_PATH(POCO_FOUNDATION_INCLUDE_DIR 
      NAMES
        Poco/Foundation.h
      PATHS
        ../../../poco-1.4.6-all/Foundation/include/
    ) 
        
    IF(WIN32)                                                             
      FIND_LIBRARY(POCO_FOUNDATION_LIB_RELEASE 
        NAMES 
          PocoFoundation
        PATHS
          ${POCO_LIB_DIRECTORY}
        )
        
      FIND_LIBRARY(POCO_FOUNDATION_LIB_DEBUG 
        NAMES 
          PocoFoundationd
        PATHS
          ${POCO_LIB_DIRECTORY}
      )
      
    ELSE(WIN32) 
      FIND_LIBRARY( POCO_FOUNDATION_LIB_RELEASE 
        NAMES
          PocoFoundation   
        PATHS
	  	  ${POCO_LIB_DIRECTORY}
          /usr/lib
          /usr/local/lib
      )   
  
      FIND_LIBRARY( POCO_FOUNDATION_LIB_DEBUG
        NAMES
          PocoFoundationd
        PATHS
	  	  ${POCO_LIB_DIRECTORY}
          /usr/lib
          /usr/local/lib
      ) 
      
    ENDIF(WIN32)  
  
    IF(POCO_FOUNDATION_INCLUDE_DIR)
      IF(POCO_FOUNDATION_LIB_RELEASE)
        SET(POCO_FOUNDATION_LIB "optimized;${POCO_FOUNDATION_LIB_RELEASE}")
        IF(POCO_FOUNDATION_LIB_DEBUG)
          SET(POCO_FOUNDATION_LIB "${POCO_FOUNDATION_LIB};debug;${POCO_FOUNDATION_LIB_DEBUG}")
        ENDIF(POCO_FOUNDATION_LIB_DEBUG)
      ENDIF(POCO_FOUNDATION_LIB_RELEASE)
    ENDIF(POCO_FOUNDATION_INCLUDE_DIR)
  
    IF(POCO_FOUNDATION_INCLUDE_DIR AND POCO_FOUNDATION_LIB)
      SET(POCO_FOUNDATION_FOUND TRUE)
      MESSAGE(STATUS "Found Poco FoundationLib: ${POCO_FOUNDATION_INCLUDE_DIR}, ${POCO_FOUNDATION_LIB}")
    ELSE(POCO_FOUNDATION_INCLUDE_DIR AND POCO_FOUNDATION_LIB)
      SET(POCO_FOUNDATION_FOUND FALSE)
      MESSAGE(STATUS "Poco FoundationLib not found.")
    ENDIF(POCO_FOUNDATION_INCLUDE_DIR AND POCO_FOUNDATION_LIB)
  
    MARK_AS_ADVANCED(POCO_FOUNDATION_LIB_RELEASE POCO_FOUNDATION_LIB_DEBUG)
    
      
  ENDIF(WITH_POCO_FOUNDATION)

ENDIF(POCO_FOUNDATION_INCLUDE_DIR AND POCO_FUNDATION_LIB )