/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "talker_constants.h"

namespace kiwi {

const talkerConstants g_talker_constants;

talkerConstants::talkerConstants() {
  KIWI_VERSION = "0.0.1";

  MAX_RESULTS = 25;

  DEFAULT_ROOMS = 3;

}

} // namespace

