/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef talker_CONSTANTS_H
#define talker_CONSTANTS_H

#include "talker_types.h"

namespace kiwi {

class talkerConstants {
 public:
  talkerConstants();

  std::string KIWI_VERSION;
  int32_t MAX_RESULTS;
  int32_t DEFAULT_ROOMS;
};

extern const talkerConstants g_talker_constants;

} // namespace

#endif
